source 'https://rubygems.org'

gem 'sinatra'
gem 'carrierwave'
gem 'puma'
gem 'slim'
gem 'sqlite3'
gem 'sequel'
gem 'carrierwave-sequel', require: 'carrierwave/sequel'
gem 'rmagick'
gem 'time_ago_in_words'
gem 'pry-byebug'
